title: sample-schema
description: sample schema
definitions: 
  name:
    title: Name
    type: string
    description: name
  age:
    title: Age
    type: string
    description: age
  created_at:
    title: CreatedAt
    type: string
    description: created_at
  tag:
    title: Tag
    type: string
    description: tag
  tags:
    title: tags
    type: array
    description: tag list
    items:
      $ref: '#/definitions/tags'
  
  user_input:
    title: User Input
    type: object
    properties:
      name: 
        $ref: '#/definitions/name'
      age:
        $ref: '#/definitions/age'

  user_output:
    title: User Output
    type: object
    properties:
      name: 
        $ref: '#/definitions/name'
      age:
        $ref: '#/definitions/age'
      created_at:
        $ref: '#/definitions/created_at'

  user_transformed:
    title: User Transformed
    type: object
    properties:
      name: 
        $ref: '#/definitions/name'
      age:
        $ref: '#/definitions/age'
      created_at:
        $ref: '#/definitions/created_at'
      tags:
        $ref: '#/definitons/tags'
        
href: https://sample-generater
links:
    - title: POST User
      description: post
      rel: self
      href: /user
      method: POST
      Schema:
        $ref: '#/definitions/user_input'
      targetSchema:
        $ref: '#/definitions/user_output'
